export enum ErrorCode {
  VALIDATION_ERROR = "VALIDATION_ERROR",

  UNAUTHORIZED = "UNAUTHORIZED",

  FORBIDDEN = "FORBIDDEN",

  NOT_FOUND = "NOT_FOUND",

  CONFLICT = "CONFLICT",

  INTERNAL_ERROR = "INTERNAL_ERROR",

  DATABASE_ERROR = "DATABASE_ERROR",

  TOOL_ERROR = "TOOL_ERROR",

  LLM_ERROR = "LLM_ERROR",

  MEMORY_ERROR = "MEMORY_ERROR",

  CONFIG_ERROR = "CONFIG_ERROR"
}